version: "3.1"

services: 
  node: 
    container_name: api-nodejs
    image: node
    ports: 
    - 3000:3000
    - 9222:9222
    volumes: 
    - ./src:/src
    working_dir: "/src"
    command: "sh start.sh" 
    depends_on: 
      - db
  db: 
    container_name: api_postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: nodejs-db
    ports:
    - 5432:5432