version: "3.1"

services: 
  web:
    container_name: api-nodejs-part2
    image: node
    ports: 
    - 3000:3000
    environment:
      - REDIS_URL=redis://cache
    volumes:
    - ./src:/src
    working_dir: "/src"
    command: "sh start.sh"
    links: 
    - redis
  redis: 
    container_name: cache
    image: redis