version: "3.1"

services: 
  node: 
    image: node
    container_name: hw-02_node
    ports: 
    - 3000:3000
    - 9222:9222
    volumes: 
    - ./src:/src
    working_dir: "/src"
    command: "sh start.sh" 
  nginx:
    image: nginx
    container_name: hw-02_nginx
    ports: 
    - 80:80
    volumes:
    - ./static:/usr/share/nginx/html