version: "3"

services:
  app:
    container_name: app
    image: node
    volumes:
    - ./src:/src
    ports:
    - 3000:3000
    - 3001:3001
    - 3002:3002
    command: sh start.sh
    depends_on:
    - db

  db:
    container_name: app_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: nodejs-db
    ports:
    - 5432:5432
